# Generated by Django 4.0.4 on 2022-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntubot', '0002_alter_user_info_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='part',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
