# Generated by Django 4.0.4 on 2022-04-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntubot', '0003_user_info_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='hint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='total_hint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='section',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
