# Generated by Django 4.0.4 on 2022-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntubot', '0004_user_info_hint_user_info_total_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='side_part',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='side_ques',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
