# Generated by Django 4.0.4 on 2022-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntubot', '0005_user_info_is_side_user_info_side_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='side_ques',
            field=models.IntegerField(default=0),
        ),
    ]
